server:
  port: ${PORT:80}
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/linkDB
    username: postgres
    password: 555555
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
