server:
  port: ${PORT:80}
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 555555
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  h2:
#    console:
#      enabled: true
#      path: /h2console/
#      settings:
#        web-allow-others: true
#spring:
#  liquibase:
#      enabled: false
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 555555
  # JPA properties
#  jpa:
#    hibernate:
#      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
    #generate-ddl: true