server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:ssl/jks_cutit4me
    key-store-type: JKS
    key-store-password: 123456
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urls_db
    username: postgres
    password: 555555
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
